### ISSUE TITLE
new rlottie version

### ISSUE THREAD

**Issue by mythodeia** [SDWebImage/librlottie-Xcode#2]
Hello @dreampiggy 
Samsung rlottie library has newer commits with some good fixes. Is there any way we can point your wrapper to the latest Samsung rlottie master branch?

thanks

**Comment by dreampiggy** [comment]
Yes. I'll update soon.

This wrapper should get update to the origin remote branch. I'll subscribe the release tab of Samsung/rlottie

**Comment by dreampiggy** [comment]
....One issue, they don't release a new version after v0.2.0 ? Just new commits to master?

Maybe not, this wrapper's release date should match the origin remote branch. If you need some Package Manager integration, like SwiftPM/CococaPods. Maybe you need to use commit as dependency or branch as dependency.

I can push new commits to update the git submodule of this repo, but not release a new version.

**Comment by dreampiggy** [comment]
Done via: 4b633a92dd5e39ab9926bba769d3b6fb2ef2bd53

**Comment by akisv** [comment]
Hello @dreampiggy . 

Is ` pod 'librlottie', :git => 'https://github.com/SDWebImage/librlottie-Xcode.git'`  working ? 

I get some errors on pod install : 

`Analyzing dependencies
Pre-downloading: `librlottie` from `https://github.com/SDWebImage/librlottie-Xcode.git`, commit `4b633a9`
[!] Failed to download 'librlottie': [!] /bin/bash -c 
set -e
sed -i.bak 's/<rlottiecommon.h>/"rlottiecommon.h"/g' './rlottie/inc/rlottie_capi.h'
sed: ./rlottie/inc/rlottie_capi.h: No such file or directory`

**Comment by dreampiggy** [comment]
Use

```ruby
pod 'librlottie', :git => 'https://github.com/SDWebImage/librlottie-Xcode.git',  :branch => "master", :submodules => true
```

See CocoaPods's wiki or issue: 

http://www.geero.net/2014/06/using-submodules-in-cocoapods-sourced-from-git/

**Comment by akisv** [comment]
thanks @dreampiggy,  it worked!
